[package]
name = "templeRun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "templeRun"
path = "src/main.rs"

[dependencies]
ggez = "0.9.3"
nalgebra = "0.33.0"
rand = "0.8.4"